language: python

python:
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c 'create database send_it_test;' -U postgres

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - pip install pytest

script:
  - pytest --cov=app tests/

after_success:
- coveralls
