language: python

python:
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c 'create database sendit_test;' -U postgres

env:
  - TRAVIS=sendit_test
  - API_ENV=TRAVIS

before_install:
  - export API_ENV=TRAVIS

install:
  - pip install -r requirements.txt
  - pip install -U python-dotenv
  - pip install coveralls

script:
  - pytest --cov=app tests/

after_success:
- coveralls
