language: python

python:
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c 'create database sendit_test;' -U postgres

before_install:
  - export APP_SETTINGS="app.config.TestingConfig"
  - export DATABASE_URL="postgresql://postgres@localhost/sendit_test"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - pytest --cov=app tests/

after_success:
- coveralls
